AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SplitFool API - AWS SAM deployment (Free Tier Optimized)

# AWS Free Tier Limits:
# Lambda: 1M requests/month, 400,000 GB-seconds compute
# DynamoDB: 25 GB storage, 25 RCU, 25 WCU (on-demand: 25M read, 25M write requests)
# API Gateway: 1M API calls/month

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs20.x
    MemorySize: 128  # Minimum memory to maximize free tier compute seconds
    ReservedConcurrentExecutions: 10  # Limit concurrent executions
    Environment:
      Variables:
        TABLE_NAME: !Ref DynamoDBTable
        NODE_OPTIONS: --enable-source-maps

Resources:
  # API Gateway
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      TracingEnabled: true

  # Lambda Function
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: lambda.handler
      # Tracing: Active  # Disabled to avoid X-Ray charges
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /
            Method: ANY
        ProxyApiGreedy:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /{proxy+}
            Method: ANY
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable

  # DynamoDB Table
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # Using provisioned capacity for free tier (25 RCU/WCU free)
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 25   # Free tier limit
        WriteCapacityUnits: 25  # Free tier limit
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 25   # Free tier limit for GSI
            WriteCapacityUnits: 25  # Free tier limit for GSI
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  # Cleanup Function
  CleanupFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: cleanup.handler
      MemorySize: 128  # Minimum memory for cleanup tasks
      Environment:
        Variables:
          TABLE_NAME: !Ref DynamoDBTable
      Events:
        ScheduledCleanup:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
            Description: Clean up groups older than 30 days
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable

  # CloudWatch Alarms for monitoring free tier usage
  LambdaInvocationsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Alert when Lambda invocations approach free tier limit
      MetricName: Invocations
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 2592000  # 30 days in seconds
      EvaluationPeriods: 1
      Threshold: 900000  # 90% of 1M free tier limit
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref ApiFunction

  DynamoDBConsumedReadAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Alert when DynamoDB read capacity usage is high
      MetricName: ConsumedReadCapacityUnits
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Period: 300  # 5 minutes
      EvaluationPeriods: 2
      Threshold: 20  # 80% of 25 RCU
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBTable

  ApiGatewayRequestsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Alert when API Gateway requests approach free tier limit
      MetricName: Count
      Namespace: AWS/ApiGateway
      Statistic: Sum
      Period: 2592000  # 30 days in seconds
      EvaluationPeriods: 1
      Threshold: 900000  # 90% of 1M free tier limit
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ApiName
          Value: !Ref Api

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${Api}.execute-api.${AWS::Region}.amazonaws.com/prod/'
  
  TableName:
    Description: DynamoDB table name
    Value: !Ref DynamoDBTable