name: Deploy Web to Cloudflare Pages

on:
  push:
    branches:
      - main
    paths:
      - 'packages/web/**'
      - 'packages/shared/**'
      - '.github/workflows/deploy-web.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build shared package
        run: pnpm --filter @split-fool/shared build

      - name: Build web app
        run: pnpm --filter @split-fool/web build:cf
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }}

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: splitfool
          directory: packages/web/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}